### ISSUE TITLE
--enable-shared doesn't enable a shared library; --disable-static doesn't disable the static libary

### ISSUE THREAD

**Issue by yurivict** [swesterfeld/liquidsfz#11]

**Comment by iurienistor** [comment]
@yurivict  This library is not intended to be shared library, it soul should be only as static. See also this: https://github.com/swesterfeld/liquidsfz/issues/7

**Comment by yurivict** [comment]
I don't buy the discussion in https://github.com/swesterfeld/liquidsfz/issues/7

If this argument is true, all our systems are compromised and vulnerable, because we only use shared libraries. In fact, the opposite is true.

**Comment by iurienistor** [comment]
@yurivict No, the systems are not vulnerable, shared libraries are necessary and a good thing. But in order to provide a shared library, there is a need for keeping the ABI compatibility which requires different stuff to be implemented in the API design. From the API I see that it has the measures to provide this, but to keep ABI compatibility between versions is more difficult if you want to add new API functionality.

Also, there is another problem that an API for plugins meets (discussed [here](http://lists.lv2plug.in/pipermail/devel-lv2plug.in/2016-March/001593.html) ), and things are more simple when there is only static linking.

**Comment by yurivict** [comment]
Shared libraries are built from the exact same source tree as the rest of the system, so there is no danger of incompatibilities in your case.

**Comment by iurienistor** [comment]
"Shared libraries are built from the exact same source tree as the rest of the system" - this doesn't provide ABI compatibility. I recommend you these articles on the subject
- https://wiki.qt.io/D-Pointer 
-  https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B

**Comment by yurivict** [comment]
API/API compatibility is ensured by having a SONAME, please see here: 

* https://stackoverflow.com/questions/12637841/what-is-the-soname-option-for-building-shared-libraries-for

The upstream author chooses a SONAME value, and when the SONAME changes users need to recompile their binaries.

**Comment by iurienistor** [comment]
"The upstream author chooses a SONAME value, and when the SONAME changes users need to recompile their binaries."... this means that the old library is no more ABI compatible with the new one that's why you need a soname or a way to indicate that. ABI compatibility is ensured by the developer ... to make sure the the memory layout of the ABI is not changed during the binary updates of the library. If this is this is changed, after an update of the shared library, the program that uses it in most of the cases will crash.

**Comment by yurivict** [comment]
The author chooses to bump SONAME when API/ABI compatibility issues can arise.
Once bumped, users would be rebuilt and would be compatible.

**Comment by swesterfeld** [comment]
If you were to enforce that all binary code the user can run is only the code you ship with the system (or distribution) then I don't have an issue with a shared library.

The case I started to think about is if binaries of the system are mixed with binaries that are from somewhere else (i.e. AppImage). I've seen more than one case where external binaries are not statically linked, but simply ship with a bunch of shared libraries they need.

So for my original concern you need (both with the same SONAME)
- a DAW from an AppImage dynamically linked against its own libliquidsfz
- a liquidsfz LV2 plugin from system dynamically linked against the system libliquidsfz

Now the DAW is started, libliquidsfz for AppImage is loaded. Then you load the plugin. The linker will use the version of libliquidsfz it already has loaded for the DAW for the plugin. If you are unlucky, the plugin will require functions that the DAW libliquidsfz doesn't have.

If you link statically, then the DAW will get its own libliquidsfz (whatever version that may be) and the LV2 plugin will get its own libliquidsfz (whatever version that may be).

**Comment by yurivict** [comment]
> The case I started to think about is if binaries of the system are mixed with binaries that are from somewhere else (i.e. AppImage). I've seen more than one case where external binaries are not statically linked, but simply ship with a bunch of shared libraries they need.

I work on FreeBSD, and no such mix can occur here. AppImage is not available/not needed here. Also you work under the assumption that various versions would accidentally mix. This probably happens on Linux, but we have a very clean ports/packages system on FreeBSD.

**Comment by swesterfeld** [comment]
Ok. I believe that mixing binaries from different locations is less likely on FreeBSD, even if part of the reason is that music software developers simply don't produce binaries for FreeBSD because it has less users than Linux (and no AppImage support). So you could use shared libs for liquidsfz.

So I think it might be reasonable to
 - default to static libs
 - support both models, let the packager decide
 - print a warning message if building with shared libs 

I don't know how difficult that would be, it was a bit of tweaking to get the current behaviour, because what we have now is neither a fully static build (because the lv2 plugin is a .so file) nor a fully shared build (because libliquidsfz is a .a file).

**Comment by yurivict** [comment]
The real reason why packages can become broken on Linux is a lack of good packaging system forcing users to rebuild software manually, to copy prebuilt binaries from some websites, or to use AppImage. They just don't have software that users need, or it is outdated.

**Comment by swesterfeld** [comment]
Now that liquidsfz 0.2.1 is available, --enable-shared/--disable-static should work as expected. So I'm closing this issue, feel free to let me know if things don't work for you.
